### ISSUE TITLE
Default transform access

### ISSUE THREAD

**Issue by rentalhost** [relative/synchrony#129]
Can I access transforms directly? I want to enable just one, for instance:

```js
await new Deobfuscator().deobfuscateSource(
  code,
  { transformChainExpressions: [new Simplify()] },
);
```

**Comment by relative** [comment]
Hi

if you would like to run a single transformer
```js
await (new Deobfuscator()).deobfuscateSource(code, {
  customTransformers: [
    ['Simplify', {} /* options */]
  ]
})
```
Defining customTransformers in the options disables all other transformers

**Comment by rentalhost** [comment]
Nice! I was using the wrong option. :D Thanks!
