### ISSUE TITLE
break long lines

### ISSUE THREAD

**Issue by 3052** [relative/synchrony#131]
using this input:

~~~js
const c=n.a.get("API.lemonade.url"),d=n.a.get("API.lemonade.urlLinear"),u=n.a.get("API.lemonade.urlVod"),p=n.a.get("API.lemonade.platform"),m=n.a.get("API.lemonade.timeout");
~~~

I get this output:

~~~js
const c = n.a.get('API.lemonade.url'), d = n.a.get('API.lemonade.urlLinear'), u = n.a.get('API.lemonade.urlVod'), p = n.a.get('API.lemonade.platform'), m = n.a.get('API.lemonade.timeout');
~~~

using another tool, I get:

~~~js
const c = n.a.get("API.lemonade.url"),
  d = n.a.get("API.lemonade.urlLinear"),
  u = n.a.get("API.lemonade.urlVod"),
  p = n.a.get("API.lemonade.platform"),
  m = n.a.get("API.lemonade.timeout");
~~~

https://richsnapp.com/tools/code-unmangler

or with another tool, I get:

~~~js
const c = n.a.get('API.lemonade.url');
const d = n.a.get('API.lemonade.urlLinear');
const u = n.a.get('API.lemonade.urlVod');
const p = n.a.get('API.lemonade.platform');
const m = n.a.get('API.lemonade.timeout');
~~~

https://restringer.tech

is is possible for Synchrony to also break long lines?

**Comment by relative** [comment]
You can use [prettier](https://npmjs.com/package/prettier) to reformat the deobfuscated script

```sh
npm install --global prettier
prettier --print-width 80 --write script.cleaned.js
```

[`--print-width 80`](https://prettier.io/docs/en/options.html#print-width) sets the desired line length
[`--write`](https://prettier.io/docs/en/cli.html#--write) replaces script.cleaned.js on disk

**Comment by 3052** [comment]
I am aware that other tools are available, I am wanting this option to be build into synchrony if possible, similar to the other tools above

**Comment by relative** [comment]
I removed prettier from the tool in 2.4.4 to reduce complexity

It is possible to achieve the same result as `prettier --print-width 80 --write script.cleaned.js` by modifying [src/cli.js](https://github.com/relative/synchrony/blob/2.4.4/src/cli.js) and invoking prettier before the fs.writeFile call on L87

**Comment by 3052** [comment]
no thanks, I will just use one of the alternatives I listed above
