### ISSUE TITLE
Host is down

### ISSUE THREAD

**Issue by KTibow** [relative/synchrony#25]
https://deobfuscate.relative.im/ is just this:
![image](https://user-images.githubusercontent.com/10727862/163721846-78c9efb0-ae3b-4e6a-a349-c4d7ab0f5d80.png)

**Comment by relative** [comment]
dns is down, will move somewhere else today. couldnt do it yesterday as the glue records prevented me from adding the domain to CloudFlare, hopefully it allows me to add it today.

**Comment by aaditya888** [comment]
still down

**Comment by relative** [comment]
resolved, please wait for DNS to propagate (4 - 48 hours)
