### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by cccs-kevin** [relative/synchrony#46]
Hi @relative, 

First of all, excellent tool!

I was wondering when a new build would be released? I want to have the `output` CLI option but it's not in v2.3.0.

Let me know what you think!

Kevin

**Comment by relative** [comment]
I just published [2.4.0](https://github.com/relative/synchrony/releases/tag/2.4.0) to npm

**Comment by cccs-kevin** [comment]
Thank you so much!
